name: CI

on:
  push:
    paths-ignore: ['**.md', '**.adoc']
  pull_request:
    paths-ignore: ['**.md', '**.adoc']

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.emacs_version == 'snapshot'}}

    strategy:
      matrix:
        emacs_version: ['27.1', '27.2', 'snapshot']

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Test the project
      run: |
        eldev prepare && eldev -p -dtT -C test
        eldev prepare && eldev -p -dtT -C compile --warnings-as-errors blamer.el
