name: check

on:
  pull_request:
  push:
    branches:
      - master
      - "feature/*"
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 27.2
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: leotaku/elisp-check@master
        with:
          file: blamer.el
          ignore_warnings: ${{ matrix.ignore_warnings }}
      - uses: leotaku/elisp-check@master
        with:
          check: ert
          ignore_warnings: ${{ matrix.ignore_warnings }}
          file: test.el
